name: Java CI/CD to GCP Cloud Run Functions

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "new-best-analyzer"
      REGION: "europe-west3" # Вкажіть ваш регіон
      WORKSPACE: "test"

    steps:
    # 1. Clone repo onto runner
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up the Java Development Kit (JDK)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Set up Gradle environment and enable caching for faster builds
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # 4. Grant execute permission for the Gradle Wrapper script
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 5. Clean/build the project (generates JAR file in build/libs/)
    - name: Build with Gradle
      run: ./gradlew clean build

    # 6. Upload the generated JAR file as a GitHub artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-app-jar                      # Name of the artifact download
        path: build/libs/*.jar                  # Path to the compiled JAR file(s)
        retention-days: 5                       # Optional: How long to keep the artifact (in days)

    # 7. Google Cloud auth
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 8. runner: gcloud CLI config
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # 9. Deploy App onto Cloud Run functions using TF-resources
    - name: Deploy to Cloud Run Functions using TF Resources
      run: |
        gcloud functions deploy java-run-function \
          --gen2 \
          --region=${{ env.REGION }} \
          --project="${{ env.PROJECT_ID }}" \
          --runtime=java17 \
          --entry-point=com.example.App \
          --source=build/libs \
          --trigger-http \
          --allow-unauthenticated \
          --service-account="${{ env.WORKSPACE }}-runtime-backend@${{ env.PROJECT_ID }}.iam.gserviceaccount.com" \
          --stage-bucket="${{ env.PROJECT_ID }}-sc-functions-${{ env.WORKSPACE }}" \
          --docker-repository="projects/${{ env.PROJECT_ID }}/locations/${{ env.REGION }}/repositories/functions-${{ env.WORKSPACE }}"
